/* Cria a sequence (recomendado: CREATE SEQUENCE é o padrão moderno) */
CREATE SEQUENCE SEQ_CLIENTE_ID;


/* Cria a tabela de clientes */
CREATE TABLE CLIENTE (
ID INTEGER NOT NULL,
NOME VARCHAR(255),
EMAIL VARCHAR(255),
TELEFONE VARCHAR(50),
SALARIO NUMERIC(12,2),
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);


/* Trigger para preencher ID automaticamente antes do INSERT */
SET TERM ^ ;
CREATE TRIGGER T_CLIENTE_ID_BI FOR CLIENTE
ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.ID IS NULL) THEN
NEW.ID = GEN_ID(SEQ_CLIENTE_ID, 1);
END
^
SET TERM ; ^